"""empty message

Revision ID: 9db590c7fd62
Revises: d9046ae5fe10
Create Date: 2017-10-03 05:33:20.957866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db590c7fd62'
down_revision = 'd9046ae5fe10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('haha_point_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fromStem_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fromStem_id'], ['stems.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('haha_point_logs')
    # ### end Alembic commands ###
