"""empty message

Revision ID: d9046ae5fe10
Revises: c9cb0e65819d
Create Date: 2017-09-14 20:43:55.078286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9046ae5fe10'
down_revision = 'c9cb0e65819d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stems_pub_date'), 'stems', ['pub_date'], unique=False)
    op.add_column('users', sa.Column('nickname', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nickname')
    op.drop_index(op.f('ix_stems_pub_date'), table_name='stems')
    op.drop_table('stems')
    # ### end Alembic commands ###
